OzFurniture/Controllers/IletisimController.cs
using Furniture.BLL.Concrete;
using Furniture.DAL.EntityFramework;
using Furniture.ENTITIES.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OzFurniture.Controllers
{
    public class IletisimController : Controller
    {
        IletisimManager im = new IletisimManager(new EfIletisimDal());
        // GET: Iletisim
        public ActionResult Index()
        {
            var iletisimvalues = im.GetList();
            return View(iletisimvalues);
        }
        [HttpGet]
        public ActionResult AddIletisim()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddIletisim(Iletisim p)
        {
            im.IletisimAdd(p);
            return RedirectToAction("Index");
        }
    }
}

OzFurniture/Views/Iletisim/AddIletisim.cshtml
@model Furniture.ENTITIES.Concrete.Iletisim
@{
    ViewBag.Title = "AddIletisim";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yeni Iletisim Ekle</h2>
<br />
@using (Html.BeginForm("AddIletisim", "Iletisim", FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Iletisim Adı:")
    @Html.TextBoxFor(x => x.Adi, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Adi)
    <br />
    @Html.Label("Iletisim Email:")
    @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Email)
    <br />
    @Html.Label("Iletisim Başlık:")
    @Html.TextBoxFor(x => x.Baslik, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Baslik)
    <br />
    @Html.Label("Iletisim Açıklama:")
    @Html.TextBoxFor(x => x.Aciklama, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Aciklama)
    <br />
    <button class="btn btn-info">İletişim Ekle</button>
    <a href="/Iletisim/Index" class="btn btn-primary">Vazgeç</a>
</div>
}

OzFurniture/Views/Iletisim/Index.cshtml
@using Furniture.ENTITIES.Concrete
@model List<Iletisim>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Adı</th>
        <th>Email</th>
        <th>Başlık</th>
        <th>Açıklama</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.IletisimId</td>
            <td>@item.Adi</td>
            <td>@item.Email</td>
            <td>@item.Baslik</td>
            <td>@item.Aciklama</td>
        </tr>
    }
</table>
<a href="/Iletisim/AddIletisim" class="btn btn-info">Yeni İletişim Ekle</a>